os: linux
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_script: npm i
script:
  - npm run build
deploy:
  provider: pages
  local_dir: build
  token: $GITHUB_TOKEN
  keep_history: false
  edge: true
  on:
    branch: master
env:
  global:
  - API_GATEWAY_INVOKE_URL: $API_GATEWAY_INVOKE_URL
  - API_GATEWAY_REGION: $API_GATEWAY_REGION
  - API_GATEWAY_ACCESSKEY: $API_GATEWAY_ACCESSKEY
  - API_GATEWAY_SECRETKEY: $API_GATEWAY_SECRETKEY
  - GITHUB_TOKEN: $GITHUB_TOKEN
  - GITHUB_EMAIL: thura.ucsy@gmail.com
  - GITHUB_USERNAME: Thura Aung
  - GITHUB_REFERENCE: github.com/thuraucsy/yen_zay.git
